In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as mp
import seaborn as sns
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

import warnings
warnings.filterwarnings("ignore")


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

d:\Final\Festivals\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 1. Importing dataset

In [3]:
# data of sales
df = pd.read_csv("../DataSet/train.csv")
# data of festivals
fd = pd.read_excel("../DataSet/festivals_base.xlsx")

# 2

changing data to object

In [ ]:
df["date"] = pd.to_datetime(df['date'])

In [4]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["weekday"] = df["date"].dt.day_name()

In [5]:
print(fd.shape)
fd.tail(13)

(190, 6)

,festival_name,festival_date,festival_type,region,impact_scale,is_regional_event
177,End_of_Season_Sale_Jul,2015-07-15,Shopping_Event,National,5,0
178,End_of_Season_Sale_Jul,2016-07-15,Shopping_Event,National,5,0
179,End_of_Season_Sale_Jul,2017-07-15,Shopping_Event,National,5,0
180,Back_to_School,2013-06-01,Shopping_Event,National,4,0
181,Back_to_School,2014-06-01,Shopping_Event,National,4,0
182,Back_to_School,2015-06-01,Shopping_Event,National,4,0
183,Back_to_School,2016-06-01,Shopping_Event,National,4,0
184,Back_to_School,2017-06-01,Shopping_Event,National,4,0
185,Big_Billion_Day,2013-10-06,Shopping_Event,National,7,0
186,Big_Billion_Day,2014-10-06,Shopping_Event,National,7,0
187,Big_Billion_Day,2015-10-13,Shopping_Event,National,7,0
188,Big_Billion_Day,2016-10-02,Shopping_Event,National,7,0
189,Big_Billion_Day,2017-09-20,Shopping_Event,National,7,0

In [6]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   festival_name      190 non-null    object
 1   festival_date      190 non-null    object
 2   festival_type      190 non-null    object
 3   region             190 non-null    object
 4   impact_scale       190 non-null    int64
 5   is_regional_event  190 non-null    int64
dtypes: int64(2), object(4)
memory usage: 9.0+ KB

# 3

In [7]:
fd["festival_date"] = pd.to_datetime(fd['festival_date'])

In [8]:
fd['festival_type'].value_counts()

festival_type
Major             90
Minor             75
Shopping_Event    25
Name: count, dtype: int64

In [9]:
fd['region'].value_counts()

region
National    130
North        25
East         15
South        15
West          5
Name: count, dtype: int64

In [10]:
fd['is_regional_event'].value_counts()

is_regional_event
0    130
1     60
Name: count, dtype: int64

In [11]:
fd['festival_name'].value_counts()

festival_name
Diwali                    5
Dhanteras                 5
Holi                      5
Eid_ul_Fitr               5
Eid_ul_Adha               5
Navratri                  5
Dussehra                  5
Raksha_Bandhan            5
Janmashtami               5
Ganesh_Chaturthi          5
Christmas                 5
Makar_Sankranti           5
Maha_Shivratri            5
Ram_Navami                5
Guru_Nanak_Jayanti        5
Bhai_Dooj                 5
Vasant_Panchami           5
Republic_Day              5
Independence_Day          5
New_Year                  5
Karwa_Chauth              5
Chhath_Puja               5
Lohri                     5
Baisakhi                  5
Durga_Puja                5
Pongal                    5
Onam                      5
Ugadi                     5
Gudi_Padwa                5
Bihu                      5
Teej                      5
Rath_Yatra                5
Govardhan_Puja            5
Wedding_Season_Start      5
End_of_Season_Sale_Jan    5
End_of_Season_Sale_Jul    5
Back_to_School            5
Big_Billion_Day           5
Name: count, dtype: int64

In [12]:
fd['impact_scale'].value_counts()

impact_scale
5     50
7     40
6     35
4     25
8     20
9     15
10     5
Name: count, dtype: int64

In [13]:
#fd["year"] = fd["festival_date"].dt.year
#fd["month"] = fd["festival_date"].dt.month
#fd["day"] = fd["festival_date"].dt.day
#fd["weekday"] = fd["festival_date"].dt.day_name()

In [14]:
fd.columns

Index(['festival_name', 'festival_date', 'festival_type', 'region',
       'impact_scale', 'is_regional_event'],
      dtype='object')

# 4

In [15]:
big_d = pd.merge(df,fd,left_on = "date" , right_on = "festival_date" , how = "left")

hear big_d have both table data mearge

# 5

In [16]:
big_d["year"] = big_d["date"].dt.year
big_d["month"] = big_d["date"].dt.month
big_d["day"] = big_d["date"].dt.day
big_d["weekday"] = big_d["date"].dt.day_name()

In [17]:
big_d.tail(16)

,date,store,item,sales,year,month,day,weekday,festival_name,festival_date,festival_type,region,impact_scale,is_regional_event
919984,2017-12-16,10,50,52,2017,12,16,Saturday,NaN,NaT,NaN,NaN,NaN,NaN
919985,2017-12-17,10,50,86,2017,12,17,Sunday,NaN,NaT,NaN,NaN,NaN,NaN
919986,2017-12-18,10,50,53,2017,12,18,Monday,NaN,NaT,NaN,NaN,NaN,NaN
919987,2017-12-19,10,50,54,2017,12,19,Tuesday,NaN,NaT,NaN,NaN,NaN,NaN
919988,2017-12-20,10,50,51,2017,12,20,Wednesday,NaN,NaT,NaN,NaN,NaN,NaN
919989,2017-12-21,10,50,63,2017,12,21,Thursday,NaN,NaT,NaN,NaN,NaN,NaN
919990,2017-12-22,10,50,75,2017,12,22,Friday,NaN,NaT,NaN,NaN,NaN,NaN
919991,2017-12-23,10,50,70,2017,12,23,Saturday,NaN,NaT,NaN,NaN,NaN,NaN
919992,2017-12-24,10,50,76,2017,12,24,Sunday,NaN,NaT,NaN,NaN,NaN,NaN
919993,2017-12-25,10,50,51,2017,12,25,Monday,Christmas,2017-12-25,Major,National,7.0,0.0
919994,2017-12-26,10,50,41,2017,12,26,Tuesday,NaN,NaT,NaN,NaN,NaN,NaN
919995,2017-12-27,10,50,63,2017,12,27,Wednesday,NaN,NaT,NaN,NaN,NaN,NaN
919996,2017-12-28,10,50,59,2017,12,28,Thursday,NaN,NaT,NaN,NaN,NaN,NaN
919997,2017-12-29,10,50,74,2017,12,29,Friday,NaN,NaT,NaN,NaN,NaN,NaN
919998,2017-12-30,10,50,62,2017,12,30,Saturday,NaN,NaT,NaN,NaN,NaN,NaN
919999,2017-12-31,10,50,82,2017,12,31,Sunday,NaN,NaT,NaN,NaN,NaN,NaN

In [18]:
big_d["impact_scale"].value_counts()

impact_scale
5.0     25000
7.0     20000
6.0     17500
4.0     12500
8.0     10000
9.0      7500
10.0     2500
Name: count, dtype: int64

In [19]:
big_d["festival_name"].value_counts()

festival_name
New_Year                  2500
Lohri                     2500
Makar_Sankranti           2500
Pongal                    2500
End_of_Season_Sale_Jan    2500
Republic_Day              2500
Vasant_Panchami           2500
Maha_Shivratri            2500
Ram_Navami                2500
Holi                      2500
Ugadi                     2500
Gudi_Padwa                2500
Baisakhi                  2500
Bihu                      2500
Back_to_School            2500
Rath_Yatra                2500
End_of_Season_Sale_Jul    2500
Eid_ul_Fitr               2500
Teej                      2500
Independence_Day          2500
Raksha_Bandhan            2500
Janmashtami               2500
Ganesh_Chaturthi          2500
Onam                      2500
Navratri                  2500
Big_Billion_Day           2500
Durga_Puja                2500
Dussehra                  2500
Eid_ul_Adha               2500
Karwa_Chauth              2500
Dhanteras                 2500
Diwali                    2500
Govardhan_Puja            2500
Bhai_Dooj                 2500
Chhath_Puja               2500
Wedding_Season_Start      2500
Guru_Nanak_Jayanti        2500
Christmas                 2500
Name: count, dtype: int64

In [20]:
big_d.index

RangeIndex(start=0, stop=920000, step=1)

hear we are changing object to numbers

In [21]:
big_d['festival_name'] = le.fit_transform(big_d["festival_name"])
big_d['weekday'] = le.fit_transform(big_d["weekday"])
big_d['festival_type'] = le.fit_transform(big_d["festival_type"])
big_d['region'] = le.fit_transform(big_d["region"])

In [22]:
#X_data.drop(["festival_date_y","festival_date_x","date","sales_X"], axis= 1)

In [23]:
big_d.columns

Index(['date', 'store', 'item', 'sales', 'year', 'month', 'day', 'weekday',
       'festival_name', 'festival_date', 'festival_type', 'region',
       'impact_scale', 'is_regional_event'],
      dtype='object')

In [24]:
# ldate = big_d["festival_date"].dropna()
# ldate

In [25]:
# # Step 1: Create an empty list to hold all expanded rows
# expanded_list = []

# # Step 2: Loop through each festival date in ldate
# for festival_date in ldate:
    
#     # Step 3: Generate the 11-day window (7 days before to 3 days after)
#     dates = pd.date_range(start=festival_date - pd.Timedelta(days=7), periods=11, freq='D')
    
#     # Step 4: Generate the offset numbers (-7 to +3)
#     offsets = list(range(-7, 4))
    
#     # Step 5: Create a mini DataFrame for this festival
#     mini_df = pd.DataFrame({
#         'festival_date': dates,
#         'days_to_next_festival': offsets,
#         'is_festival_day': [1 if offset == 0 else 0 for offset in offsets],
#         'pre_festival_week': [1 if -7 <= offset <= 0 else 0 for offset in offsets]
#     })
    
#     # Step 6: Add this mini DataFrame to our list
#     expanded_list.append(mini_df)

# # Step 7: Combine all mini DataFrames into one big DataFrame
# fd_expanded = pd.concat(expanded_list, ignore_index=True)

# # Step 8: Check the result
# print(f"Created {len(fd_expanded)} rows")
# print(fd_expanded.head(15))

In [26]:
ldate = big_d["festival_date"].dropna().unique()

offsets = range(-7, 4)

fd_expanded = pd.DataFrame({
    "festival_date": [
        date + pd.Timedelta(days=offset)
        for date in ldate
        for offset in offsets
    ],
    "days_to_next_festival": [
        offset
        for date in ldate
        for offset in offsets
    ]
})

fd_expanded["is_festival_day"] = (
    fd_expanded["days_to_next_festival"] == 0
).astype("int8")

fd_expanded["pre_festival_week"] = (
    fd_expanded["days_to_next_festival"].between(-7, 0)
).astype("int8")

In [27]:
final_df = pd.merge(big_d, fd_expanded, left_on='date', right_on='festival_date', how='left')

In [28]:
final_df.drop(["festival_date_x", "festival_date_y","date"],axis = 1,inplace = True )

In [29]:
final_df["impact_scale"] = final_df["impact_scale"].fillna(0)
#final_df["festival_date_x"] = final_df["festival_date_x"].fillna("no")
final_df["is_festival_day"] = final_df["is_festival_day"].fillna(0)

In [30]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314500 entries, 0 to 1314499
Data columns (total 15 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   store                  1314500 non-null  int64
 1   item                   1314500 non-null  int64
 2   sales                  1314500 non-null  int64
 3   year                   1314500 non-null  int32
 4   month                  1314500 non-null  int32
 5   day                    1314500 non-null  int32
 6   weekday                1314500 non-null  int64
 7   festival_name          1314500 non-null  int64
 8   festival_type          1314500 non-null  int64
 9   region                 1314500 non-null  int64
 10  impact_scale           1314500 non-null  float64
 11  is_regional_event      212000 non-null   float64
 12  days_to_next_festival  981000 non-null   float64
 13  is_festival_day        1314500 non-null  float64
 14  pre_festival_week      981000 non-null   float64
dtypes: float64(5), int32(3), int64(7)
memory usage: 135.4 MB

In [31]:
final_df.isnull().sum()

store                          0
item                           0
sales                          0
year                           0
month                          0
day                            0
weekday                        0
festival_name                  0
festival_type                  0
region                         0
impact_scale                   0
is_regional_event        1102500
days_to_next_festival     333500
is_festival_day                0
pre_festival_week         333500
dtype: int64

In [32]:
print(final_df["is_festival_day"].unique())
print(final_df["is_festival_day"].dtype)

[1. 0.]
float64

In [33]:
big_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920000 entries, 0 to 919999
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   date               920000 non-null  datetime64[ns]
 1   store              920000 non-null  int64
 2   item               920000 non-null  int64
 3   sales              920000 non-null  int64
 4   year               920000 non-null  int32
 5   month              920000 non-null  int32
 6   day                920000 non-null  int32
 7   weekday            920000 non-null  int64
 8   festival_name      920000 non-null  int64
 9   festival_date      95000 non-null   datetime64[ns]
 10  festival_type      920000 non-null  int64
 11  region             920000 non-null  int64
 12  impact_scale       95000 non-null   float64
 13  is_regional_event  95000 non-null   float64
dtypes: datetime64[ns](2), float64(2), int32(3), int64(7)
memory usage: 87.7 MB

In [34]:
big_d['impact_scale'] = le.fit_transform(big_d["impact_scale"])
#big_d['festival_date_x'] = le.fit_transform(big_d["festival_date_x"])
#big_d['is_festival_day'] = le.fit_transform(big_d["is_festival_day"])

data sales shift

In [35]:
#final_df["sales_lag_1"] = final_df["sales"]
#final_df["sales_lag_1"] = final_df["sales_lag_1"].shift(periods = 1)

In [36]:
# CORRECT way to create lag features
#final_df['sales_lag_1'] = final_df.groupby(['store', 'item'])['sales'].shift(1)
#final_df['sales_lag_7'] = final_df.groupby(['store', 'item'])['sales'].shift(7)

In [37]:
#final_df["sales_X"] = final_df["impact_scale"] * final_df["is_festival_day"]

In [38]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314500 entries, 0 to 1314499
Data columns (total 15 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   store                  1314500 non-null  int64
 1   item                   1314500 non-null  int64
 2   sales                  1314500 non-null  int64
 3   year                   1314500 non-null  int32
 4   month                  1314500 non-null  int32
 5   day                    1314500 non-null  int32
 6   weekday                1314500 non-null  int64
 7   festival_name          1314500 non-null  int64
 8   festival_type          1314500 non-null  int64
 9   region                 1314500 non-null  int64
 10  impact_scale           1314500 non-null  float64
 11  is_regional_event      212000 non-null   float64
 12  days_to_next_festival  981000 non-null   float64
 13  is_festival_day        1314500 non-null  float64
 14  pre_festival_week      981000 non-null   float64
dtypes: float64(5), int32(3), int64(7)
memory usage: 135.4 MB

In [39]:
final_df.isnull().sum()

store                          0
item                           0
sales                          0
year                           0
month                          0
day                            0
weekday                        0
festival_name                  0
festival_type                  0
region                         0
impact_scale                   0
is_regional_event        1102500
days_to_next_festival     333500
is_festival_day                0
pre_festival_week         333500
dtype: int64

In [40]:
final_df

,store,item,sales,year,month,day,weekday,festival_name,festival_type,region,impact_scale,is_regional_event,days_to_next_festival,is_festival_day,pre_festival_week
0,1,1,13,2013,1,1,5,27,1,1,5.0,0.0,0.0,1.0,1.0
1,1,1,11,2013,1,2,6,38,3,5,0.0,NaN,1.0,0.0,0.0
2,1,1,14,2013,1,3,4,38,3,5,0.0,NaN,2.0,0.0,0.0
3,1,1,13,2013,1,4,0,38,3,5,0.0,NaN,3.0,0.0,0.0
4,1,1,10,2013,1,5,2,38,3,5,0.0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314495,10,50,63,2017,12,27,6,38,3,5,0.0,NaN,2.0,0.0,0.0
1314496,10,50,59,2017,12,28,4,38,3,5,0.0,NaN,3.0,0.0,0.0
1314497,10,50,74,2017,12,29,0,38,3,5,0.0,NaN,NaN,0.0,NaN
1314498,10,50,62,2017,12,30,2,38,3,5,0.0,NaN,NaN,0.0,NaN
1314499,10,50,82,2017,12,31,3,38,3,5,0.0,NaN,NaN,0.0,NaN

In [41]:
from sklearn.model_selection import train_test_split

# dividing data around year

In [42]:
X_data = final_df[final_df["year"] < 2017]
Y_data = final_df[final_df["year"] == 2017]

# x_data (before 2017)

In [43]:
X = X_data.drop(["sales"], axis = 1)
y = X_data["sales"]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Y_data (2017)

In [45]:
Y_ka_X = Y_data.drop(["sales"], axis = 1)
Y_ka_y = Y_data["sales"]

In [46]:
from sklearn.metrics import accuracy_score

In [47]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

# model name Ramdom frost

In [48]:
#rf.fit(X_train , y_train)

RandomForestRegressor(max_features='sqrt', n_jobs=-1, random_state=42)

In [49]:
# from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score , root_mean_squared_error

# # Predict
# predictions = rf.predict(Y_ka_X )

# # Calculate metrics
# mae = mean_absolute_error(Y_ka_y, predictions)

# r2 = r2_score(Y_ka_y, predictions)

# print(f"MAE: {mae:.2f}")

# print(f"R² Score: {r2:.2f}")

1st -> 
MAE: 16.40
R² Score: 0.47

2nd -> MAE: 2.39
R² Score: 0.49

3rd -> MAE: 2.63
R² Score: 0.42

4th -> MAE: 9.83
R² Score: 0.82 (max_depth = 10)

MAE: 8.39
R² Score: 0.88  (at max_depth = 15)

MAE: 7.63
R² Score: 0.90

MAE: 10.11
R² Score: 0.81

MAE: 7.18
R² Score: 0.91

In [50]:
import xgboost as xg

In [51]:
XGmodel = xg.XGBRegressor()

In [52]:
X_train

,store,item,year,month,day,weekday,festival_name,festival_type,region,impact_scale,is_regional_event,days_to_next_festival,is_festival_day,pre_festival_week
842692,1,33,2015,10,1,4,38,3,5,0.0,NaN,3.0,0.0,0.0
896587,2,35,2013,3,15,0,38,3,5,0.0,NaN,-4.0,0.0,1.0
8102,4,1,2013,6,15,2,38,3,5,0.0,NaN,NaN,0.0,NaN
492236,8,19,2014,2,16,3,38,3,5,0.0,NaN,NaN,0.0,NaN
119267,6,5,2014,10,21,5,7,0,1,9.0,0.0,-3.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136125,2,6,2016,11,4,0,38,3,5,0.0,NaN,3.0,0.0,0.0
321032,3,13,2013,8,14,6,38,3,5,0.0,NaN,-1.0,0.0,1.0
163366,3,7,2013,10,5,2,26,0,1,8.0,0.0,0.0,1.0,1.0
831367,7,32,2014,2,6,4,38,3,5,0.0,NaN,2.0,0.0,0.0
150857,8,6,2014,11,7,0,38,3,5,0.0,NaN,1.0,0.0,0.0

# model name XG

In [53]:
#XGmodel.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [54]:
y_pred = XGmodel.predict(Y_ka_X)

In [55]:
# Calculate metrics
mae = mean_absolute_error(Y_ka_y, y_pred)

r2 = r2_score(Y_ka_y, y_pred)

print(f"MAE: {mae:.2f}")

print(f"R² Score: {r2:.2f}")

NameError: name 'mean_absolute_error' is not defined

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# PART 1: FEATURE IMPORTANCE PLOT
# ==========================================

# 1. Get the importance scores from your trained model
# (Make sure to replace 'xgb_model' with the actual variable name of your trained XGBoost model)
importances = XGmodel.feature_importances_

# 2. Create a DataFrame to make it easy to sort and plot
feature_imp_df = pd.DataFrame({
    'Feature': X.columns, # Replace 'X' with your actual features dataframe name
    'Importance': importances
})

# 3. Sort the features from highest importance to lowest
feature_imp_df = feature_imp_df.sort_values(by='Importance', ascending=False)

# 4. Plot the results
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_imp_df, palette='viridis')
plt.title('XGBoost Feature Importance')
plt.xlabel('Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

In [58]:
import pickle 

with open("XGmodel.pkl" , "wb") as file:
    pickle.dump(XGmodel,file)

with open("RandomFroest.pkl" , "wb") as file:
    pickle.dump(rf,file)